# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Voiyd < Formula
  desc "Lightweight, eventdriven orchestration for container workloads"
  homepage "https://github.com/amimof/voiyd"
  url "https://github.com/amimof/voiyd/archive/refs/tags/v0.0.12.tar.gz"
  sha256 "6f1333b8c648245c068245d60690dfaa70e25935017ba6a23b60ec32167413ea"
  license "Apache-2.0"

  def install
    bin.install Dir["voiydctl-*"].first => "voiydctl"
  end
end
